apiVersion: v1
kind: Service
metadata:
  name: rarible-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: rarible-api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080